[env]
OPENCV_INCLUDE_PATHS = { value = "third_party/opencv-4.5.5-static/include", relative = true }
OPENCV_LINK_PATHS = { value = "third_party/opencv-4.5.5-static/x64/vc17/staticlib", relative = true }
OPENCV_LINK_LIBS = "static=opencv_features2d455,static=opencv_imgproc455,static=opencv_core455,static=zlib"
CLANG_PATH = "C:/Program Files/LLVM/bin/clang.exe"
OPENCV_MSVC_CRT = "static"
