pub use windows::core::{Error, Result};

pub use windows::Win32::Foundation::{HWND, LPARAM, LRESULT, RECT, WPARAM};

pub use windows::Win32::UI::WindowsAndMessaging::{
    CS_DBLCLKS, CS_HREDRAW, CS_OWNDC, SIZE_MAXIMIZED, SIZE_MINIMIZED, SIZE_RESTORED,
    SWP_NOACTIVATE, SWP_NOZORDER, WM_CLOSE, WM_CREATE, WM_DESTROY, WM_DISPLAYCHANGE, WM_DPICHANGED,
    WM_HOTKEY, WM_PAINT, WM_SETCURSOR, WM_SIZE, WM_TIMER,
};
